[project]
name = "suggestions-version-4"
version = "4.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiobotocore>=2.21.1",
    "disnake[speed]>=2.10.1",
    "fastnanoid>=0.4.1",
    "function-cooldowns>=2.1.0",
    "logoo>=1.5.1",
    "orjson>=3.10.15",
    "piccolo[all,postgres]>=1.0.0",
    "redis[hiredis]>=5.2.1",
    "skelmis-commons>=1.4.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "fakeredis>=2.27.0",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
]
